# Build from github package
services:
  server:
    container_name: disastream_api
    image: ghcr.io/echelon35/disastreamapi:latest
    env_file:
      - ./.env.prod
    environment:
      NODE_ENV: production
    ports:
      - 4003:4003